[workspace]
resolver = "2"
members = ["programs/*"]

[workspace.package]
version = "0.0.1"

[workspace.dependencies]
anchor-lang = "=0.31.1"
anchor-spl = "=0.31.1"
solana-program = "=2.1.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 20

[profile.release.build-override]
opt-level = 0
incremental = false
codegen-units = 20

[profile.fast]
codegen-units = 20
inherits = "release"

[profile.fast.build-override]
opt-level = 0
codegen-units = 20
