# Basic
hard_tabs = false            # Use spaces instead of tabs
tab_spaces = 4               # Set the number of spaces per tab
max_width = 100
use_small_heuristics = "Max"
# Imports
imports_granularity = "Crate"       # Merge imports from the same crate
group_imports = "StdExternalCrate"  # Group standard, external, and internal imports separately
reorder_imports = true              # Ensure imports are sorted alphabetically
# Consistency
newline_style = "Unix"
# Format comments
comment_width = 100
wrap_comments = true
# Misc
chain_width = 80
spaces_around_ranges = false
binop_separator = "Back"
reorder_impl_items = false
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
edition = "2021"
