[package]
name = "layerzero"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[features]
gas_profile = []

[dependencies]
starknet = "2.14.0"
openzeppelin = "2.0.0"
lz_utils = { path = "../libs/lz_utils" }
enumerable_set = { path = "../libs/enumerable_set" }
multisig = { path = "../libs/multisig" }

[dev-dependencies]
snforge_std = "0.49.0"
assert_macros = "2.12.0"
starkware_utils_testing = { git = "https://github.com/starkware-libs/starkware-starknet-utils", rev = "e1955423808045de868987b8fb0b43f5cbdf5699" }

[lib]

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_scarb_plugin", "snforge_std"]

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
